### ISSUE TITLE
[Feature] - Users and Oauth

### ISSUE THREAD

**Issue by leodomingo** [cavdailyonline/unicorn#11]
App is currently configured to just let everybody in, going to create users and authentication.

**Comment by jnayak1** [comment]
Probably no need for oauth unless you want to do Facebook/twitter integrations. Django has its own [authentication](https://docs.djangoproject.com/en/1.10/topics/auth/) system.

**Comment by leodomingo** [comment]
Yeah that's on me, I meant normal authentication

**Comment by jnayak1** [comment]
Also, Author and django.contrib.auth User [should be one-to-one](https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#extending-the-existing-user-model)

**Comment by leodomingo** [comment]
Authors are the people that actually write the articles, but Users are the 16 JB members that will actually be uploading content.

**Comment by jnayak1** [comment]
Ah, I see
