### ISSUE TITLE
Generic Views

### ISSUE THREAD

**Issue by jnayak1** [cavdailyonline/unicorn#19]
Evaluate whether we should switch to [generic views](https://docs.djangoproject.com/en/1.10/intro/tutorial04/#use-generic-views-less-code-is-better). It looks like generic views are meant for simple CRUD apps like the one we are currently buidling and would significantly reduce amount of code.

**Comment by leodomingo** [comment]
Absolutely right, no need to be doing the piecemeal views that are currently in the app. I'm going to assign this to myself and restructure the views.

**Comment by jnayak1** [comment]
Also evaluate [form views](https://docs.djangoproject.com/en/1.10/topics/class-based-views/generic-editing/)

**Comment by leodomingo** [comment]
This was handled with PR #31
