### ISSUE TITLE
Author's school

### ISSUE THREAD

**Issue by jnayak1** [cavdailyonline/unicorn#2]
Right now an Author's school is a charfield. This should be a choice field IMO. That way its easy to search by school. It makes validation easier.

https://github.com/leodomingo/thecavalierdani/blob/master/mysite/unicorn/models.py#L13

**Comment by ml3ha** [comment]
@jnayak1 @leodomingo Jesse and I discussed this briefly and we think the school field should remain a CharField and handled on the front end.

**Comment by leodomingo** [comment]
Handled with school options in PR #33
